console.log("Javascript is working!");
//consol.log("isthis working?");
let number1 = 6;
let number2 = 4;
let average = (number1+number2)/2
console.log("The average of the two numbers is " + average+ ".");
let radius = 5;
let area= Math.PI*radius**2;
console.log("the area of the circle is " + area + "." );
let acceleration= 10;
let time= 5;
let changeY =.5*acceleration*time**2;
console.log("the displacement is "+ changeY + ".") ;
let a = 4;
let b=5;
let c=1;
let disc = Math.sqrt(b**2 -4*a*c);
let solution1 = (-b + disc)/(2*a);
let solution2= (-b - disc)/(2*a);
console.log("the solutions to the quadratic are "+ solution1 + " and " +solution2 + ".");